### PR TITLE
bug 93/sign in not working

### LINKED ISSUE #93: Bug - signing in redirects to the starting page, not landing page

### PR DESCRIPTION
**Pull request by BrentTB**
The issue happened as the redirect acted faster than saving the session in req.session, and so middleware was added to ensure the req object is reloaded
Test code was simplified by removing earlier test to retry when sign in did not work
Test code was simplified to use guest user instead of signing in with test account

closes #93

### CODE REVIEW

File: src/app.js [hunk 1]
```diff
@@ -30,6 +31,8 @@ app.use(
 
 app.use('/', Router)
 
+app.use(welcomeController.waitForSession)
```
Comment (samcohen1) [inline src/app.js:34]: This is a smart fix to the bug.

File: src/controller/welcomeController.js [hunk 2]
```diff
@@ -8,6 +8,23 @@ exports.welcome = async (req, res) => {
   res.sendFile(path.join(__dirname, '../public/html', 'welcome.html'))
 }
 
+exports.waitForSession = (req, res, next) => {
```
Comment (samcohen1) [inline src/controller/welcomeController.js:11]: This problem has been smartly handled to ensure waiting for the session to load.

**Review by samcohen1 — COMMENTED** [review]
The bug has been fixed and some problematic code removed, which has improved the codebase.
Please fix the problem of tests timing out before it can be merged fully.

**Review by samcohen1 — COMMENTED** [review]
Temporary fix that will be changed later.

**Review by samcohen1 — COMMENTED** [review]
Changes should be fixed with this addition. Well done

**Comment by samcohen1** [comment]
There have been some changes to the sign in that should assist with faulty testing conditions that were produced as a result of the scaling and ADR decisions as the application grew. This is important, well done.
