### PR TITLE
Bug fix 124/canvas colour

### LINKED ISSUE #124: Bug - shape tool resets canvas to the wrong colour

### PR DESCRIPTION
**Pull request by BrentTB**
the can was colour was sometimes reset to a colour other than white, which was fixed

closes #124

### CODE REVIEW

File: src/public/js/drawingBoard.js [hunk 1]
```diff
@@ -665,15 +665,18 @@ clearButton.addEventListener('click', function () {
...
-function undo () {
+function undo() {
   if (index <= 0) {
     undoButton.disabled = true
   }
   redoButton.disabled = false
   index -= 1
   drawingShapeStart -= 1
   if (index <= -1) {
+    const previousFillStyle = context.fillStyle
```
Comment (samcohen1) [inline src/public/js/drawingBoard.js:676]: This should fix the bug, well done.

**Review by samcohen1 — COMMENTED** [review]
The bug appears to be fixed. Well done
