### PR TITLE
Scoring bug fix

### LINKED ISSUE #107: Bug - error with tests

### PR DESCRIPTION
**Pull request by samcohen1**
There was a problem with the scoring, it has been fixed.

Closes #107

### CODE REVIEW

File: src/public/js/drawingBoard.js [hunk 1]
```diff
@@ -235,15 +235,15 @@ socket.on('votingResult', function (result) {
...
+  if (result.result.twoMax) {
+    message += `Two members received an equal number of votes - Imposter Victory!\n${result.result.imposter} Wins!`
   } else {
     message = `${result.result.mostVotedUser} was voted imposter with ${result.result.votes} votes.`
-  }
-  if (result.isImposter) {
-    message += ' They were the imposter! Crewmate Victory!'
-  } else {
-    message += ` They were NOT the imposter! Victory for imposter ${result.imposter}!`
+    if (result.result.isImposter) {
```
Comment (RudolphTorlage) [inline src/public/js/drawingBoard.js:242]: Does this work in an elimination-style format? Or does the imposter win by not being voted in that one round?

File: src/server.js [hunk 2]
```diff
@@ -395,13 +395,12 @@ function determineResults(room) {
...
+  if (mostVotedUser !== null) {
     Object.entries(room.leaderboard).forEach(([username, score]) => {
       if (
-        (mostVotedUser !== room.imposterUsername &&
-          username === room.imposterUsername) ||
-        (mostVotedUser === room.imposterUsername &&
-          username !== room.imposterUsername)
+        (!isImposter && username === room.imposterUsername) ||
+        (twoMax && username === room.imposterUsername) ||
+        (isImposter && username !== room.imposterUsername && !twoMax)
```
Comment (RudolphTorlage) [inline src/server.js:403]: What is the variable twoMax?

**Review by RudolphTorlage — CHANGES_REQUESTED** [review]
Please be more descriptive with variable names. Knowing what twoMax does is unclear.
Tests failed.

File: src/server.js (hunk 2 above)
Comment (samcohen1) [reply src/server.js:403]: It is used when two people receive an equal number of votes. The variable name will be changed to make that clearer.

File: src/public/js/drawingBoard.js (hunk 1 above)
Comment (samcohen1) [reply src/public/js/drawingBoard.js:242]: The imposter wins by not being voted in that round. The eliminations can be a further recommendation for commercial release.

Comment (BrentTB) [reply src/public/js/drawingBoard.js:242]: I believe an elimination would not be the best choice, as it would stop a user from interacting for a whole game, which can be quite long

File: tests/drawingBoard.spec.js
Comment (BrentTB) [inline tests/drawingBoard.spec.js:1]: the tests now load all three pages at once, instead of one at a time, which improves test speed, well done
the test also ensures the roomID has been generated before other pages use it, which is needed for when the tests are run faster than the webserver

**Review by BrentTB — APPROVED** [review]
The code is good, the fixed necessitated by @RudolphTorlage were added, the testing procedure was improved. Good job

File: src/server.js (hunk 2 above)
Comment (samcohen1) [reply src/server.js]: The variable name has been changed to indicate what it does.
