### PR TITLE
bug 95/draw page size

### LINKED ISSUE #95: bug - draw page screen-size smaller than the page

### PR DESCRIPTION
**Pull request by BrentTB**
changed drawing canvas size

closes #95

### CODE REVIEW

File: src/public/js/drawingBoard.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ socket.on('normal', () => {
 
 const canvas = document.getElementById('canvas')
 canvas.width = window.innerWidth - 300
-canvas.height = window.innerHeight - 300
+canvas.height = window.innerHeight - 350
```
Comment (samcohen1) [inline src/public/js/drawingBoard.js:100]: Wow, very simple change to fix something important!

**Review by samcohen1 — COMMENTED** [review]
This very simple change should fix the drawing page size, well done.

File: src/public/js/drawingBoard.js (hunk 1 above)
Comment (BrentTB) [reply src/public/js/drawingBoard.js:100]: yes, it is amazing how sometimes a tiny change can have such a large effect on the gameplay and game experience
