### PR TITLE
function call changed

### LINKED ISSUE #77: Save image not working
The save image button throws an error and no image is saved to the database

### PR DESCRIPTION
**Pull request by BrentTB**
save image issue is fixed

closes #77

### CODE REVIEW

File: src/server.js [hunk 1]
```diff
@@ -107,7 +107,7 @@ io.on('connection', (socket) => {
     console.log('here:')
     console.log(rooms[roomId].gameID)
 
-    getDrawingsGame.saveDrawing(
+    dbController.saveDrawing(
```
Comment (samcohen1) [inline src/server.js:110]: Thank you for fixing this bug.

**Review by samcohen1 — COMMENTED** [review]
The bug is fixed.
