### PR TITLE
Bug fix 84/timer not working

### LINKED ISSUE #84: Bug - timer is not working

### PR DESCRIPTION
**Pull request by BrentTB**
Both timers should be working now, for the input prompt and for drawing
the timer can still be changed through URL parameters for testing
the timer tests were reintroduced

closes #84

### CODE REVIEW

File: src/public/js/drawingBoard.js [hunk 1]
```diff
@@ -743,4 +704,8 @@ function hideWaitingContainer() {
   waitingContainer.style.display = 'none'
 }
 
+function showWaitingContainer() {
```
Comment (samcohen1) [inline src/public/js/drawingBoard.js:707]: The code for the timer looks good. It is succinct and achieves its required functionality.

File: tests/drawingBoard.spec.js [hunk 2]
```diff
@@ -202,159 +202,197 @@ test('player can exit game', async ({ context }) => {
...
+      await page1.$eval(
+        '#drawingCountdownBar',
+        (e) => getComputedStyle(e).width
+      )
+    )
+
+    // check if the width of the timer bar has decreased
+    expect(laterWidth).toBeLessThan(initialWidth)
+  })
+})
```
Comment (samcohen1) [inline tests/drawingBoard.spec.js:395]: Tests are well written and cover the timer content.

**Review by samcohen1 — COMMENTED** [review]
The timer has been successfully implemented, well done.
