### PR TITLE
Bug fix 87/undo button gray

### LINKED ISSUE #87: Bug - undo button only appears not gray from the second stroke

### PR DESCRIPTION
**Pull request by BrentTB**
The undo button now appears after the first stroke

closes #87

### CODE REVIEW

File: src/controller/dbController.js [hunk 1]
```diff
@@ -71,7 +71,6 @@ exports.newGame = (names, host) => {
       if (error) {
         reject(error)
       } else {
-        console.log(`Created game with ID: ${results.rows[0].game_id}`)
```
Comment (samcohen1) [inline src/controller/dbController.js:74]: Removing unnecessary console.logs is good practice

**Review by samcohen1 — COMMENTED** [review]
This bug has been fixed and the code can be merged into main.
